services:
  - type: web
    name: quan-ly-thoi-trang
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --timeout 120 run:app
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: MAIL_SERVER
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: "465"
      - key: MAIL_USE_TLS
        value: "False"
      - key: MAIL_USE_SSL
        value: "True"
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: PYTHON_VERSION
        value: "3.11.0"
